import { useState, useEffect, useRef, useCallback } from "react";
import { useLocation } from "wouter";
import { getStorageData } from "@/lib/storage";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Label } from "@/components/ui/label";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { CheckCircle2, Clock, List } from "lucide-react";

// ─── PASSAGE CONTENT ─────────────────────────────────────────────────────────

const PASSAGES: Record<string, { title: string; body: string }> = {
  P1: {
    title: "Crop-growing skyscrapers",
    body: `By the year 2050, nearly 80% of the Earth's population will live in urban centres. Applying the most conservative estimates to current demographic trends, the human population will increase by about three billion people by then. An estimated 109 hectares of new land (about 20% larger than Brazil) will be needed to grow enough food to feed them, if traditional farming methods continue as they are practised today. At present, throughout the world, over 80% of the land that is suitable for raising crops is in use. Historically, some 15% of that has been laid waste by poor management practices. What can be done to ensure enough food for the world's population to live on?

The concept of indoor farming is not new, since hothouse production of tomatoes and other produce has been in vogue for some time. What is new is the urgent need to scale up this technology to accommodate another three billion people. Many believe an entirely new approach to indoor farming is required, employing cutting-edge technologies. One such proposal is for the 'Vertical Farm'. The concept is of multi-storey buildings in which food crops are grown in environmentally controlled conditions. Situated in the heart of urban centres, these buildings would bring the advantages of controlled-environment agriculture to bear on the health of the community.

The advantages of vertical farming are numerous. First, crops would be produced all year round, since the growing season would no longer be determined by the sun's rays or temperature fluctuations—the lack of seasonality could be compensated for by the use of LED lighting and other artificial means. Second, there would be no weather-related crop failures due to floods, drought, or pest infestations. Third, all the water needed for irrigation would be recycled and there would be no need for chemical pesticides or fertilisers.

A major drawback of any controlled-environment vertical farm is the high cost of artificial lighting. The system would require an enormous amount of electrical energy that—if generated by burning fossil fuels—would negate the very environmental benefits that the system is supposed to provide. Renewable energy sources, particularly wind and solar power, would have to be used. Excess energy from daytime operations could be stored in high-capacity batteries for use at night.

Critics of vertical farms argue that the concept is merely a solution looking for a problem—that the world is not as close to a food crisis as some alarmists suggest. They also point to the high initial capital costs of constructing skyscraper farms in expensive downtown locations. Proponents counter that when all factors are considered—proximity to urban markets, elimination of transport costs, reduced waste from field-to-table delays—vertical farming becomes more economically viable than it first appears.

Research into vertical farming technology continues in universities and start-ups around the world. Scientists are working on optimising light frequencies for maximum photosynthetic efficiency and developing hydroponic and aeroponic growing systems that use up to 95% less water than conventional agriculture. Whether or not vertical farms become a mainstream solution, they represent an exciting convergence of architecture, engineering, and agronomy aimed at feeding tomorrow's cities.`,
  },
  P2: {
    title: "The Way to Happiness",
    body: `Psychologists have long debated what makes people happy. Early research focused on material circumstances: income, job security, marital status, and physical health. While these factors do matter, studies consistently show they account for a surprisingly small fraction of variance in self-reported well-being. A person who wins the lottery, for instance, returns to roughly their previous happiness level within a year of the windfall.

The concept of a 'hedonic baseline' or 'happiness set-point' suggests that each individual has a genetically determined level of happiness to which they naturally gravitate. Sonja Lyubomirsky's influential model proposes that roughly 50% of our happiness is determined by genetics, 10% by life circumstances, and 40% by intentional activity—things we actively choose to do or think. This last category is where psychologists believe we have the most leverage.

Among intentional activities that reliably boost well-being, gratitude practices rank highly. Participants who wrote down three things they were grateful for each day reported significantly higher happiness and lower depression scores after just three weeks. Equally powerful is the practice of 'acts of kindness': individuals who performed five random acts of kindness in a single day showed measurable increases in positive affect that lasted for several days.

Social connection is another robust predictor of happiness. Robert Putnam's research on social capital shows that people embedded in dense social networks—not necessarily large ones, but deep ones—report greater life satisfaction. The quality of relationships matters far more than quantity. Even brief positive interactions with strangers, such as chatting to a barista or making eye contact and smiling at a passerby, have been shown to improve mood.

Exercise offers perhaps the most reliably documented mood-boosting effect of any lifestyle factor. A landmark meta-analysis found that regular aerobic exercise was as effective as antidepressant medication in treating mild to moderate depression. The mechanisms are multiple: endorphin release, increased neurogenesis in the hippocampus, improved sleep quality, and enhanced self-efficacy all contribute.

Finally, the research on flow—the state of total absorption in a challenging activity—suggests that designing our lives to include more flow experiences is a powerful pathway to lasting happiness. Whether it is rock climbing, playing chess, cooking an ambitious recipe, or writing code, activities that sit at the sweet spot between boredom and anxiety generate their own intrinsic reward.`,
  },
  P3: {
    title: "Motivating Voters",
    body: `A
Low voter turnout has plagued democracies for decades. In the United States, mid-term election participation rarely exceeds 40%; in many European countries, local elections draw fewer than one in three eligible voters. Scholars and practitioners have long searched for effective interventions to reverse this decline.

B
Traditional get-out-the-vote (GOTV) campaigns relied on blanket mailings and phone canvassing. Meta-analyses of hundreds of randomised trials show that these tactics, while cheap, produce only modest and inconsistent gains. Door-to-door canvassing by genuine volunteers is substantially more effective—increasing turnout by two to three percentage points—but is labour-intensive and costly.

C
A breakthrough came from the application of social norms research. When voters received mail stating that their neighbours had voted—and that their own voting record would be shared with neighbours—turnout increased by an extraordinary eight percentage points in one study. The power of social observation and peer comparison proved far stronger than appeals to civic duty.

D
Digital nudges have emerged as a new frontier. Facebook's 2010 midterm experiment reached 61 million users and found that displaying a social message ('Your friends voted') increased real-world turnout by about 340,000 people—a small percentage effect but a massive absolute impact at scale. Critically, the social message outperformed the simple informational message ('Go vote today') by a factor of two.

E
Psychological reactance poses a challenge for all voter mobilisation efforts. When people feel their autonomy is threatened—when they perceive they are being told what to do—they sometimes respond by doing the opposite. Messaging that frames voting as a personal choice and emphasises identity ('Be a voter' rather than 'Go vote') is more effective because it aligns with people's desire for self-determination.

F
The timing of voter contact matters enormously. Research consistently finds that contact in the final 72 hours before an election produces the highest lift in turnout. Earlier contact, while useful for increasing political awareness, does not reliably translate into action when the election is still weeks away.

G
Convenience interventions—automatic voter registration, expanded early voting, vote-by-mail, and polling place accessibility—have been shown to produce consistent, if modest, gains in participation. These reforms work by reducing the transactional costs of voting, making it marginally easier for those who are already motivated but facing situational barriers.

H
Some researchers caution that focusing solely on increasing the quantity of votes risks neglecting quality. An uninformed vote may, in some analyses, be worse than an abstention. Others dispute this view strongly, arguing that participation is intrinsically valuable in a democracy regardless of the voter's level of knowledge. The debate reflects a fundamental tension in democratic theory that remains unresolved.`,
  },
};

// ─── QUESTION DATA ────────────────────────────────────────────────────────────

type QType = "fill" | "tfng" | "paragraph" | "table" | "mcq";

interface QuestionGroup {
  id: string;
  passageId: string;
  type: QType;
  title: string;
  instructions: string;
  range: [number, number];
  questions: QuestionItem[];
  tableConfig?: { headers: string[]; rows: { label: string; blanks: number[] }[] };
}

interface QuestionItem {
  num: number;
  stem?: string;
  preBlank?: string;
  postBlank?: string;
  options?: string[];
  paragraphOptions?: string[];
}

const PARTS: {
  id: string;
  label: string;
  rangeLabel: string;
  range: [number, number];
  passageId: string;
  groups: QuestionGroup[];
}[] = [
  {
    id: "part1",
    label: "PART 1",
    rangeLabel: "1 to 13 Questions",
    range: [1, 13],
    passageId: "P1",
    groups: [
      {
        id: "g1",
        passageId: "P1",
        type: "fill",
        title: "Questions 1–7",
        instructions:
          "Complete the sentences below.\nChoose NO MORE THAN TWO WORDS from the passage for each answer.\nWrite your answers in boxes 1–7 on your answer sheet.",
        range: [1, 7],
        questions: [
          { num: 1, preBlank: "Some food plants, including", postBlank: "are already grown indoors." },
          { num: 2, preBlank: "By 2050 the world population will have grown by around", postBlank: "people." },
          { num: 3, preBlank: "Vertical farms situated in", postBlank: "would benefit local communities." },
          { num: 4, preBlank: "Indoor vertical farms would not be affected by", postBlank: "or pest attacks." },
          { num: 5, preBlank: "The water used in vertical farming can be", postBlank: "and reused." },
          { num: 6, preBlank: "Vertical farms would need to use", postBlank: "to generate clean energy." },
          { num: 7, preBlank: "Scientists are working on systems that need up to 95% less", postBlank: "than traditional farming." },
        ],
      },
      {
        id: "g2",
        passageId: "P1",
        type: "tfng",
        title: "Questions 8–13",
        instructions:
          "Do the following statements agree with the information given in Reading Passage?\nIn boxes 8–13 on your answer sheet, write\nTRUE\t\tif the statement agrees with the information\nFALSE\t\tif the statement contradicts the information\nNOT GIVEN\tif there is no information on this",
        range: [8, 13],
        questions: [
          { num: 8, stem: "Methods for predicting the Earth's population have recently changed." },
          { num: 9, stem: "The crops produced in vertical farms will depend on the season." },
          { num: 10, stem: "Fertilisers will be needed for certain crops in vertical farms." },
          { num: 11, stem: "A renewable energy source would be essential for vertical farms to be environmentally beneficial." },
          { num: 12, stem: "The initial cost of building vertical farms is considered a significant disadvantage by some." },
          { num: 13, stem: "Vertical farming research is currently only conducted in North America." },
        ],
      },
    ],
  },
  {
    id: "part2",
    label: "PART 2",
    rangeLabel: "14 to 26 Questions",
    range: [14, 26],
    passageId: "P2",
    groups: [
      {
        id: "g3",
        passageId: "P2",
        type: "fill",
        title: "Questions 14–19",
        instructions:
          "Complete the summary below.\nChoose ONE WORD ONLY from the passage for each answer.\nWrite your answers in boxes 14–19 on your answer sheet.",
        range: [14, 19],
        questions: [
          { num: 14, preBlank: "According to researchers, around half of our happiness is determined by", postBlank: "." },
          { num: 15, preBlank: "People who kept a daily", postBlank: "of things to be thankful for felt happier within three weeks." },
          { num: 16, preBlank: "Performing random", postBlank: "for others raises positive feelings for several days." },
          { num: 17, preBlank: "Research shows that the", postBlank: "of our relationships is more important than their number." },
          { num: 18, preBlank: "Aerobic exercise has been shown to be as effective as", postBlank: "medication for mild depression." },
          { num: 19, preBlank: "Activities that sit between boredom and anxiety can produce a state called", postBlank: "." },
        ],
      },
      {
        id: "g4",
        passageId: "P2",
        type: "fill",
        title: "Questions 20–26",
        instructions:
          "Label the diagram below.\nChoose ONE WORD from the passage for each answer.\nWrite your answers in boxes 20–26 on your answer sheet.",
        range: [20, 26],
        questions: [
          { num: 20, preBlank: "The model assigns 50% of happiness to", postBlank: "factors." },
          { num: 21, preBlank: "Life circumstances account for just", postBlank: "percent of happiness variance." },
          { num: 22, preBlank: "The remaining 40% is attributed to", postBlank: "activity." },
          { num: 23, preBlank: "Social", postBlank: "refers to the networks of relationships that support well-being." },
          { num: 24, preBlank: "Exercise leads to increased", postBlank: "in the hippocampus." },
          { num: 25, preBlank: "Flow occurs when a task is both challenging and personally", postBlank: "." },
          { num: 26, preBlank: "Flow generates its own", postBlank: "reward, independent of external motivations." },
        ],
      },
    ],
  },
  {
    id: "part3",
    label: "PART 3",
    rangeLabel: "27 to 40 Questions",
    range: [27, 40],
    passageId: "P3",
    groups: [
      {
        id: "g5",
        passageId: "P3",
        type: "paragraph",
        title: "Questions 27–29",
        instructions:
          "Reading Passage 3 has eight paragraphs A–H\nWhich paragraph contains the following information?\nWrite the correct letter, A–H, in boxes 27–29 on your answer sheet.",
        range: [27, 29],
        questions: [
          { num: 27, stem: "A description of how social comparison can dramatically increase voting rates." },
          { num: 28, stem: "A contrast between two types of digital messages and their relative effectiveness." },
          { num: 29, stem: "An argument that reducing practical barriers to voting produces consistent results." },
        ],
      },
      {
        id: "g6",
        passageId: "P3",
        type: "table",
        title: "Questions 30–36",
        instructions:
          "Complete the table below.\nChoose ONE WORD from the passage for each answer.\nWrite your answers in boxes 30–36 on your answer sheet.",
        range: [30, 36],
        tableConfig: {
          headers: ["Method", "Key Finding"],
          rows: [
            { label: "Blanket mailings and phone calls", blanks: [30] },
            { label: "Door-to-door canvassing by volunteers", blanks: [31] },
            { label: "Social norms mailer (neighbours voted)", blanks: [32] },
            { label: "Facebook social message", blanks: [33] },
            { label: "Identity-based framing", blanks: [34] },
            { label: "Final 72-hour contact", blanks: [35] },
            { label: "Automatic registration and early voting", blanks: [36] },
          ],
        },
        questions: [
          { num: 30, stem: "produce only modest and _____ gains" },
          { num: 31, stem: "more effective but labour-_____ and costly" },
          { num: 32, stem: "increased turnout by an extraordinary eight _____ points" },
          { num: 33, stem: "increased real-world turnout by about 340,000 _____" },
          { num: 34, stem: "reduces psychological _____ by framing voting as a choice" },
          { num: 35, stem: "produces the highest _____ in turnout" },
          { num: 36, stem: "reduces transactional _____ of voting" },
        ],
      },
      {
        id: "g7",
        passageId: "P3",
        type: "mcq",
        title: "Questions 37–40",
        instructions:
          "Choose the correct letter, A, B, C, or D.\nWrite the correct letter in boxes 37–40 on your answer sheet.",
        range: [37, 40],
        questions: [
          {
            num: 37,
            stem: "According to paragraph B, what is the main disadvantage of door-to-door canvassing?",
            options: [
              "A  It has no measurable effect on turnout.",
              "B  It requires a large amount of effort and money.",
              "C  Voters react negatively to being approached at home.",
              "D  It is only effective in local elections.",
            ],
          },
          {
            num: 38,
            stem: "What does the research on psychological reactance (paragraph E) suggest about voter messaging?",
            options: [
              "A  Messages should clearly instruct people to vote.",
              "B  Messages should highlight civic duty and obligation.",
              "C  Messages should make voting feel like a personal, voluntary choice.",
              "D  Messages should compare voters with non-voters negatively.",
            ],
          },
          {
            num: 39,
            stem: "Which of the following best describes convenience interventions mentioned in paragraph G?",
            options: [
              "A  They produce large increases in turnout among all voter groups.",
              "B  They are primarily aimed at uninformed voters.",
              "C  They reduce situational obstacles to voting for motivated individuals.",
              "D  They are more effective than social norm messages.",
            ],
          },
          {
            num: 40,
            stem: "What unresolved debate does the writer refer to in paragraph H?",
            options: [
              "A  Whether social media should be regulated during elections.",
              "B  Whether voter participation is inherently valuable regardless of knowledge.",
              "C  Whether convenience measures can replace canvassing.",
              "D  Whether digital nudges violate voter privacy.",
            ],
          },
        ],
      },
    ],
  },
];

// ─── HELPERS ──────────────────────────────────────────────────────────────────

function formatTime(secs: number) {
  const m = Math.floor(secs / 60).toString().padStart(2, "0");
  const s = (secs % 60).toString().padStart(2, "0");
  return `${m} : ${s}`;
}

const TOTAL_QUESTIONS = 40;
const INITIAL_TIME = 60 * 60;

// ─── COMPONENT ────────────────────────────────────────────────────────────────

export default function ReadingTest() {
  const [, setLocation] = useLocation();
  const session = getStorageData().session;

  useEffect(() => {
    if (!session.loggedIn) setLocation("/");
  }, [session.loggedIn, setLocation]);

  const [answers, setAnswers] = useState<Record<number, string>>({});
  const [activePart, setActivePart] = useState(0);
  const [timeLeft, setTimeLeft] = useState(INITIAL_TIME);
  const [showReview, setShowReview] = useState(false);
  const [showSubmit, setShowSubmit] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const rightRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (submitted) return;
    const id = setInterval(() => {
      setTimeLeft((t) => {
        if (t <= 1) {
          clearInterval(id);
          setSubmitted(true);
          return 0;
        }
        return t - 1;
      });
    }, 1000);
    return () => clearInterval(id);
  }, [submitted]);

  const setAnswer = useCallback((num: number, val: string) => {
    setAnswers((prev) => ({ ...prev, [num]: val }));
  }, []);

  const answeredCount = Object.values(answers).filter((v) => v && v.trim() !== "").length;
  const currentPart = PARTS[activePart];

  const scrollToGroup = (groupId: string) => {
    const el = document.getElementById(`group-${groupId}`);
    if (el && rightRef.current) {
      const offset = el.offsetTop - rightRef.current.offsetTop;
      rightRef.current.scrollTop = offset - 16;
    }
  };

  if (submitted) {
    return (
      <div className="h-screen flex flex-col items-center justify-center bg-background gap-6">
        <CheckCircle2 className="w-16 h-16 text-green-500" />
        <h1 className="text-3xl font-bold">Test Submitted</h1>
        <p className="text-muted-foreground text-lg">
          You answered {answeredCount} of {TOTAL_QUESTIONS} questions.
        </p>
        <Button onClick={() => setLocation("/dashboard")} data-testid="btn-back-dashboard">
          Return to Dashboard
        </Button>
      </div>
    );
  }

  return (
    <div className="h-screen flex flex-col overflow-hidden bg-background" data-testid="reading-test-page">
      {/* ── TOP HEADER ── */}
      <header className="flex-shrink-0 h-12 border-b bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))] flex items-center px-4 gap-4 z-10">
        <span className="font-semibold text-sm tracking-wide truncate flex-1">
          C11 Reading Test 1 AC
        </span>
        <div className="flex items-center gap-1.5 text-sm font-mono bg-black/20 px-3 py-1 rounded">
          <Clock className="w-3.5 h-3.5" />
          <span data-testid="test-timer">{formatTime(timeLeft)}</span>
        </div>
        <Button
          size="sm"
          variant="outline"
          className="h-7 text-xs bg-transparent border-white/40 text-white hover:bg-white/10 hover:text-white"
          onClick={() => setShowReview(true)}
          data-testid="btn-review"
        >
          <List className="w-3.5 h-3.5 mr-1" />
          REVIEW
        </Button>
        <Button
          size="sm"
          className="h-7 text-xs bg-white text-[hsl(var(--primary))] hover:bg-white/90 font-semibold"
          onClick={() => setShowSubmit(true)}
          data-testid="btn-submit-test"
        >
          SUBMIT
        </Button>
      </header>

      {/* ── MAIN TWO-PANEL ── */}
      <div className="flex-1 flex overflow-hidden">
        {/* LEFT: Passage */}
        <div className="w-1/2 overflow-y-auto border-r bg-card" data-testid="passage-panel">
          <div className="p-6 max-w-2xl mx-auto">
            <h2 className="text-xl font-bold mb-4 text-foreground">
              {PASSAGES[currentPart.passageId].title}
            </h2>
            <div className="text-sm leading-7 text-foreground whitespace-pre-wrap">
              {PASSAGES[currentPart.passageId].body}
            </div>
          </div>
        </div>

        {/* RIGHT: Questions */}
        <div className="w-1/2 overflow-y-auto bg-muted/10" ref={rightRef} data-testid="questions-panel">
          <div className="p-6 space-y-10">
            {currentPart.groups.map((group) => (
              <QuestionGroupBlock
                key={group.id}
                group={group}
                answers={answers}
                setAnswer={setAnswer}
              />
            ))}
          </div>
        </div>
      </div>

      {/* ── BOTTOM PART + QUESTION NAV ── */}
      <footer className="flex-shrink-0 border-t bg-card" data-testid="test-footer">
        {/* Part tabs */}
        <div className="flex border-b">
          {PARTS.map((part, idx) => (
            <button
              key={part.id}
              onClick={() => { setActivePart(idx); scrollToGroup(part.groups[0].id); }}
              data-testid={`part-tab-${idx + 1}`}
              className={`flex-1 py-2 text-xs font-semibold tracking-wide transition-colors ${
                activePart === idx
                  ? "bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))]"
                  : "text-muted-foreground hover:bg-muted"
              }`}
            >
              {part.label}: {part.rangeLabel}
            </button>
          ))}
        </div>

        {/* Question number grid */}
        <div className="flex items-center gap-1 px-4 py-2 flex-wrap">
          {Array.from({ length: TOTAL_QUESTIONS }, (_, i) => i + 1).map((num) => {
            const isCurrentPart =
              num >= currentPart.range[0] && num <= currentPart.range[1];
            const isAnswered = !!(answers[num] && answers[num].trim() !== "");
            return (
              <button
                key={num}
                data-testid={`q-nav-${num}`}
                onClick={() => {
                  const partIdx = PARTS.findIndex(
                    (p) => num >= p.range[0] && num <= p.range[1]
                  );
                  if (partIdx !== -1) setActivePart(partIdx);
                  setTimeout(() => {
                    const el = document.getElementById(`q-${num}`);
                    if (el && rightRef.current) {
                      rightRef.current.scrollTop =
                        el.offsetTop - rightRef.current.offsetTop - 16;
                    }
                  }, 50);
                }}
                className={`w-7 h-7 text-xs rounded font-medium transition-all ${
                  isAnswered
                    ? "bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))]"
                    : isCurrentPart
                    ? "border border-[hsl(var(--primary))] text-[hsl(var(--primary))]"
                    : "bg-muted text-muted-foreground"
                }`}
              >
                {num}
              </button>
            );
          })}
          <span className="ml-auto text-xs text-muted-foreground whitespace-nowrap">
            {answeredCount}/{TOTAL_QUESTIONS} answered
          </span>
        </div>
      </footer>

      {/* ── REVIEW DIALOG ── */}
      <AlertDialog open={showReview} onOpenChange={setShowReview}>
        <AlertDialogContent className="max-w-lg">
          <AlertDialogHeader>
            <AlertDialogTitle>Question Review</AlertDialogTitle>
            <AlertDialogDescription>
              {answeredCount} of {TOTAL_QUESTIONS} questions answered. Unanswered questions are
              highlighted.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <div className="grid grid-cols-5 gap-2 py-2 max-h-64 overflow-y-auto">
            {Array.from({ length: TOTAL_QUESTIONS }, (_, i) => i + 1).map((num) => {
              const isAnswered = !!(answers[num] && answers[num].trim() !== "");
              return (
                <div
                  key={num}
                  className={`h-9 flex items-center justify-center rounded text-sm font-semibold ${
                    isAnswered
                      ? "bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))]"
                      : "bg-muted border border-destructive/40 text-destructive"
                  }`}
                >
                  {num}
                </div>
              );
            })}
          </div>
          <AlertDialogFooter>
            <AlertDialogCancel data-testid="review-close">Continue Test</AlertDialogCancel>
            <AlertDialogAction
              onClick={() => { setShowReview(false); setShowSubmit(true); }}
              data-testid="review-submit"
            >
              Submit Anyway
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* ── SUBMIT DIALOG ── */}
      <AlertDialog open={showSubmit} onOpenChange={setShowSubmit}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Submit Test?</AlertDialogTitle>
            <AlertDialogDescription>
              You have answered {answeredCount} of {TOTAL_QUESTIONS} questions.{" "}
              {TOTAL_QUESTIONS - answeredCount > 0 && (
                <span className="text-destructive font-medium">
                  {TOTAL_QUESTIONS - answeredCount} question(s) are still unanswered.
                </span>
              )}{" "}
              Once submitted, you cannot make changes.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel data-testid="cancel-submit">Go Back</AlertDialogCancel>
            <AlertDialogAction
              onClick={() => setSubmitted(true)}
              data-testid="confirm-submit"
            >
              Submit Test
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}

// ─── QUESTION GROUP BLOCK ─────────────────────────────────────────────────────

function QuestionGroupBlock({
  group,
  answers,
  setAnswer,
}: {
  group: QuestionGroup;
  answers: Record<number, string>;
  setAnswer: (num: number, val: string) => void;
}) {
  return (
    <div id={`group-${group.id}`} className="space-y-4">
      <h3 className="text-sm font-bold text-foreground">{group.title}</h3>
      <div className="text-xs text-muted-foreground whitespace-pre-line leading-relaxed border-l-4 border-[hsl(var(--primary))] pl-3">
        {group.instructions}
      </div>

      {group.type === "fill" && (
        <FillGroup group={group} answers={answers} setAnswer={setAnswer} />
      )}
      {group.type === "tfng" && (
        <TFNGGroup group={group} answers={answers} setAnswer={setAnswer} />
      )}
      {group.type === "paragraph" && (
        <ParagraphGroup group={group} answers={answers} setAnswer={setAnswer} />
      )}
      {group.type === "table" && (
        <TableGroup group={group} answers={answers} setAnswer={setAnswer} />
      )}
      {group.type === "mcq" && (
        <MCQGroup group={group} answers={answers} setAnswer={setAnswer} />
      )}
    </div>
  );
}

// ─── Fill-blank ───────────────────────────────────────────────────────────────

function FillGroup({
  group,
  answers,
  setAnswer,
}: {
  group: QuestionGroup;
  answers: Record<number, string>;
  setAnswer: (num: number, val: string) => void;
}) {
  return (
    <div className="space-y-3">
      {group.questions.map((q) => (
        <div key={q.num} id={`q-${q.num}`} className="flex items-start gap-2">
          <span className="text-xs font-bold w-6 pt-2 shrink-0 text-[hsl(var(--primary))]">{q.num}</span>
          <div className="flex-1 text-sm leading-7 text-foreground flex flex-wrap items-center gap-x-1">
            <span>{q.preBlank}</span>
            <Input
              className="inline-flex h-7 w-36 text-xs px-2 border-0 border-b border-border rounded-none bg-transparent focus-visible:ring-0 focus-visible:border-[hsl(var(--primary))]"
              placeholder="write answer"
              value={answers[q.num] || ""}
              onChange={(e) => setAnswer(q.num, e.target.value)}
              data-testid={`input-q${q.num}`}
            />
            {q.postBlank && <span>{q.postBlank}</span>}
          </div>
        </div>
      ))}
    </div>
  );
}

// ─── True / False / Not Given ─────────────────────────────────────────────────

const TFNG_OPTS = ["TRUE", "FALSE", "NOT GIVEN"];

function TFNGGroup({
  group,
  answers,
  setAnswer,
}: {
  group: QuestionGroup;
  answers: Record<number, string>;
  setAnswer: (num: number, val: string) => void;
}) {
  return (
    <div className="space-y-4">
      {group.questions.map((q) => (
        <div key={q.num} id={`q-${q.num}`} className="space-y-2">
          <div className="flex gap-2 items-start">
            <span className="text-xs font-bold w-6 shrink-0 pt-0.5 text-[hsl(var(--primary))]">{q.num}</span>
            <span className="text-sm text-foreground leading-relaxed">{q.stem}</span>
          </div>
          <div className="ml-8 flex gap-2 flex-wrap">
            {TFNG_OPTS.map((opt) => {
              const selected = answers[q.num] === opt;
              return (
                <button
                  key={opt}
                  onClick={() => setAnswer(q.num, selected ? "" : opt)}
                  data-testid={`tfng-${q.num}-${opt}`}
                  className={`px-3 py-1 rounded text-xs font-semibold border transition-colors ${
                    selected
                      ? "bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))] border-[hsl(var(--primary))]"
                      : "border-border text-muted-foreground hover:border-[hsl(var(--primary))] hover:text-[hsl(var(--primary))]"
                  }`}
                >
                  {opt}
                </button>
              );
            })}
          </div>
        </div>
      ))}
    </div>
  );
}

// ─── Paragraph matching ───────────────────────────────────────────────────────

const PARAGRAPH_OPTS = ["A", "B", "C", "D", "E", "F", "G", "H"];

function ParagraphGroup({
  group,
  answers,
  setAnswer,
}: {
  group: QuestionGroup;
  answers: Record<number, string>;
  setAnswer: (num: number, val: string) => void;
}) {
  return (
    <div className="space-y-4">
      {group.questions.map((q) => (
        <div key={q.num} id={`q-${q.num}`} className="flex items-start gap-2">
          <span className="text-xs font-bold w-6 shrink-0 pt-2 text-[hsl(var(--primary))]">{q.num}</span>
          <div className="flex-1 space-y-1">
            <p className="text-sm text-foreground leading-relaxed">{q.stem}</p>
            <div className="flex flex-wrap gap-1 pt-1">
              {PARAGRAPH_OPTS.map((opt) => {
                const selected = answers[q.num] === opt;
                return (
                  <button
                    key={opt}
                    onClick={() => setAnswer(q.num, selected ? "" : opt)}
                    data-testid={`para-${q.num}-${opt}`}
                    className={`w-8 h-8 rounded text-xs font-bold border transition-colors ${
                      selected
                        ? "bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))] border-[hsl(var(--primary))]"
                        : "border-border text-muted-foreground hover:border-[hsl(var(--primary))] hover:text-[hsl(var(--primary))]"
                    }`}
                  >
                    {opt}
                  </button>
                );
              })}
            </div>
          </div>
        </div>
      ))}
    </div>
  );
}

// ─── Table completion ─────────────────────────────────────────────────────────

function TableGroup({
  group,
  answers,
  setAnswer,
}: {
  group: QuestionGroup;
  answers: Record<number, string>;
  setAnswer: (num: number, val: string) => void;
}) {
  const cfg = group.tableConfig!;
  const qByNum = Object.fromEntries(group.questions.map((q) => [q.num, q]));

  return (
    <div className="overflow-x-auto">
      <table className="w-full text-xs border border-border">
        <thead>
          <tr className="bg-muted">
            {cfg.headers.map((h) => (
              <th key={h} className="text-left px-3 py-2 border-b border-border font-semibold">
                {h}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {cfg.rows.map((row, rIdx) => {
            const qNum = row.blanks[0];
            const q = qByNum[qNum];
            return (
              <tr key={rIdx} className="border-b border-border last:border-0">
                <td className="px-3 py-2 text-muted-foreground align-top">{row.label}</td>
                <td className="px-3 py-2 align-top" id={`q-${qNum}`}>
                  <div className="flex items-center gap-1 flex-wrap text-foreground leading-6">
                    <span>{q.stem?.split("_____")[0]}</span>
                    <Input
                      className="inline-flex h-6 w-24 text-xs px-2 border-0 border-b border-border rounded-none bg-transparent focus-visible:ring-0 focus-visible:border-[hsl(var(--primary))]"
                      placeholder={`${qNum}`}
                      value={answers[qNum] || ""}
                      onChange={(e) => setAnswer(qNum, e.target.value)}
                      data-testid={`input-q${qNum}`}
                    />
                    <span>{q.stem?.split("_____")[1]}</span>
                  </div>
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  );
}

// ─── Multiple Choice ──────────────────────────────────────────────────────────

function MCQGroup({
  group,
  answers,
  setAnswer,
}: {
  group: QuestionGroup;
  answers: Record<number, string>;
  setAnswer: (num: number, val: string) => void;
}) {
  return (
    <div className="space-y-6">
      {group.questions.map((q) => (
        <div key={q.num} id={`q-${q.num}`} className="space-y-2">
          <div className="flex gap-2 items-start">
            <span className="text-xs font-bold w-6 shrink-0 pt-0.5 text-[hsl(var(--primary))]">{q.num}</span>
            <span className="text-sm font-medium text-foreground leading-relaxed">{q.stem}</span>
          </div>
          <div className="ml-8 space-y-1">
            {q.options?.map((opt, oIdx) => {
              const letter = ["A", "B", "C", "D"][oIdx];
              const selected = answers[q.num] === letter;
              return (
                <button
                  key={oIdx}
                  onClick={() => setAnswer(q.num, selected ? "" : letter)}
                  data-testid={`mcq-${q.num}-${letter}`}
                  className={`w-full text-left text-xs px-3 py-2 rounded border transition-colors ${
                    selected
                      ? "bg-[hsl(var(--primary))]/10 border-[hsl(var(--primary))] text-[hsl(var(--primary))] font-medium"
                      : "border-border text-foreground hover:bg-muted"
                  }`}
                >
                  {opt}
                </button>
              );
            })}
          </div>
        </div>
      ))}
    </div>
  );
}
